/* GENERATED BY H2 DB*/

drop table authority if exists;
drop table cities if exists;
drop table comments if exists;
drop table routes if exists;
drop table user_authority if exists;
drop table users if exists;
create table authority
(
    name varchar(50) not null,
    primary key (name)
);
create table cities
(
    id          bigint generated by default as identity,
    country     varchar(50),
    description varchar(100),
    name        varchar(50),
    primary key (id)
);
create table airports
(
    id             bigint generated by default as identity,
    altitude       bigint,
    dst            varchar(255),
    external_id    bigint not null,
    iata           varchar(255),
    icao           varchar(255),
    latitude       decimal(19, 2),
    longitude      decimal(19, 2),
    name           varchar(100),
    source         varchar(255),
    timezone_olson varchar(255),
    timezone_utc   float,
    type           varchar(255),
    city           bigint not null,
    primary key (id)
);
create table comments
(
    id     bigint generated by default as identity,
    text   varchar(1000),
    author bigint not null,
    city   bigint not null,
    created_at TIMESTAMP NOT NULL,
    modified_at TIMESTAMP NOT NULL,
    primary key (id)
);
create table routes
(
    id                       bigint generated by default as identity,
    airline                  varchar(255),
    airline_id               varchar(255),
    code_share               varchar(255),
    destination_airport_code varchar(255),
    destination_airport_id   bigint,
    equipment                varchar(255),
    price                    decimal(19, 2) not null,
    source_airport_code      varchar(255),
    source_airport_id        bigint,
    stops                    integer        not null,
    primary key (id)
);
create table user_authority
(
    user_id        bigint      not null,
    authority_name varchar(50) not null,
    primary key (user_id, authority_name)
);
create table users
(
    id            bigint generated by default as identity,
    first_name    varchar(50),
    last_name     varchar(50),
    password_hash varchar(60) not null,
    username      varchar(50) not null,
    primary key (id)
);
alter table cities
    add constraint UKjw9iqkmfmoxtpy601efs7758f unique (name, country);
alter table users
    add constraint UK_r43af9ap4edm43mmtq01oddj6 unique (username);
alter table airports
    add constraint FK4hqpgunvtnvcs2ylj0op71e8d foreign key (city) references cities;
alter table comments
    add constraint FKp6ilf8rosuwl497khjofovggk foreign key (author) references users;
alter table comments
    add constraint FKl7f1bqsuphw72xv4m9xdb6sdl foreign key (city) references cities;
alter table user_authority
    add constraint FK6ktglpl5mjosa283rvken2py5 foreign key (authority_name) references authority;
alter table user_authority
    add constraint FKhi46vu7680y1hwvmnnuh4cybx foreign key (user_id) references users;